### ISSUE TITLE
i can't create certificate in last version of docker-flow-proxy

### ISSUE THREAD

**Issue by codati** [n1b0r/docker-flow-proxy-letsencrypt#1]
hi,
i can't not create certificate in last version of docker-flow-proxy
what has changed in haproxy config:
```
acl domain_myservice hdr_dom(host) -i domaine.com
```
to
```
acl domain_myservice hdr(host) -i domaine.com
```

if rule of docker-flow-proxy-letsencrypt after rule for service
the rule of service match first for domaine.com/.well-known/acme-challenge/XXX

for quick fixe:
rename docker service docker-flow-proxy-letsencrypt to 10_docker-flow-proxy-letsencrypt 
(rule in haproxy are sort in alphabetical)

**Comment by n1b0r** [comment]
I opened an issue on docker-flow-proxy to correctly handle it [#164](https://github.com/vfarcic/docker-flow-proxy/issues/164).

Why did you close this issue, did you find an elegant workaround ?
