### ISSUE TITLE
Can not use dns chalenge

### ISSUE THREAD

**Issue by hopkins-tk** [n1b0r/docker-flow-proxy-letsencrypt#11]
### Description
When I try to use DNS challenge by setting `CERTBOT_OPTIONS` to `--manual --manual-public-ip-logging-ok --preferred-challenges dns --manual-auth-hook /certbot-hooks/azure-authenticator.sh --manual-cleanup-hook /certbot-hooks/azure-cleanup.sh` (we have created and mounted the authenticator hooks for Azure), I get following error:
```
PluginSelectionError: Too many flags setting configurators/installers/authenticators 'webroot' -> 'manual'
```

### Root cause
It is due to always setting `--webroot` and `--webroot-path` in *dfple.py*,
if I tweak the file not to include those, everything works as a charm.

### Possible solution
It should probably be decided based on the challenge method, whether to include those or not.

**Comment by n1b0r** [comment]
This should be fixed in release 0.5, you should pull latest version.

I did not make any tests, but you could set env var `CERTBOT_CHALLENGE=dns` (something different than webroot), which should **deactivate** `--webroot` and `--webroot-path` arguments in certbot cmd.

Then you should be able to give your extra parameters to certbot cmd using `CERTBOT_OPTIONS` env var.

Please reopen if this solution do not handle your case.

**Comment by n1b0r** [comment]
I am currently implementing several enhancement with CERTBOT_CHALLENGE.

Is your `/certbot-hooks/azure-authenticator.sh` a custom script ? How many time your wait for DNS propagation ?

**Comment by hopkins-tk** [comment]
Yes, it is a custom script - I haven't found it anywhere.

I am thinking about making PR to https://github.com/certbot/certbot, but haven't had time yet...
- but there are some Authenticators for other DNS providers

Inspiration was taken from here: https://certbot.eff.org/docs/using.html#pre-and-post-validation-hooks

As per your question - I don't wait at all...

To prevent caching of the record though, I set TTL for the ACME record to low number:
```
az network dns record-set txt add-record -g "$AZURE_RESOURCE_GROUP" -z "$ZONE" -n "$RECORD_SET_NAME" -v "$CERTBOT_VALIDATION" --ttl 5
```
