### ISSUE TITLE
Automatic renewal of certificates

### ISSUE THREAD

**Issue by patrickleet** [n1b0r/docker-flow-proxy-letsencrypt#2]
> The automatic renew certificates feature is currently a work in progress.

Any idea of timelines for working on this feature?

**Comment by n1b0r** [comment]
I am currently thinking about the implementation.
I would like to keep things simple and I am thinking adding a new service into the proxy stack to handle the cron job.

I would like to use the **busybox** image which has **crond** built-in. This service could periodically send a **notify-services** request to **swarm-listener** and let **letsencrypt** renew certs if needed.

That could be very easy to handle, and could be ready soon.

Do you have any thoughts about it ?

**Comment by vfarcic** [comment]
If you're OK with Go, I can give you the code that does Cron-like scheduling. It is very lightweight and served me well by now. Also, there are quite a few LE libraries in Go (e.g. https://github.com/ericchiang/letsencrypt, https://github.com/xenolf/lego) that would allow relatively easy development.

I'm not trying to convince you to use Go. It's more like a brainstorming from my part...

**Comment by n1b0r** [comment]
We have same mecanics in python, I will produce something for renewal by the end of the week. Stay tuned.

**Comment by n1b0r** [comment]
implemented using a crond job in release 0.3
