### ISSUE TITLE
Certs are not loaded by DFP if they already exist

### ISSUE THREAD

**Issue by Routhinator** [n1b0r/docker-flow-proxy-letsencrypt#5]
Before I get into the issue, I want to thank you for this container as the other letsencrypt container for DFP doesn't allow defining the cert domains at the service level and this is exactly what I needed.

Now, this worked great until I updated the restart policy on this and DFP and restarted them both. Now DFP is serving HTTP over HTTPS with no cert... 

I am using the volumes method for storage. I don't have the letsencrypt volume mounted to the DFP container as it seems that's for non-LE certs to me, but maybe that's all I'm missing.

This seems to still work if I ask for a new cert for a new service, so it seems to only be an issue with pre-existing, valid LE certs.

**Comment by n1b0r** [comment]
Hello, sorry for the delayed reply.

To keep persistance on DFP certs, you need to use a volume to keep those certs available after restart.
This has been implemented following the issue : https://github.com/vfarcic/docker-flow-proxy/issues/142

Please tell me if its what you were looking for.
