### ISSUE TITLE
Cron renewal not working due to typo in entrypoint.sh

### ISSUE THREAD

**Issue by koby1** [n1b0r/docker-flow-proxy-letsencrypt#6]
After noticing that cron was not notifying services to renew certificates, I noticed the below typo in entrypoint.sh:

currently    :8080/v1/docker-flow-swarm-listner/notify-services
should be   :8080/v1/docker-flow-swarm-listener/notify-services

Otherwise everything is working perfectly.  Thank you for creating this very useful container!

**Comment by n1b0r** [comment]
Thanks for reporting it !
This has been fixed in 0.4 release, you should pull the latest image.
