### ISSUE TITLE
Configuration of DFP when using secrets

### ISSUE THREAD

**Issue by patrickleet** [n1b0r/docker-flow-proxy-letsencrypt#8]
Hey just tried out secret mode, and ended up reverting to using volumes. It seems like the current configuration in the README is missing something. When the proxy reloads, the certs are lost. Wouldn't a secrets key be required in the DFP config to tell it where to mount the cert secret?

**Comment by patrickleet** [comment]
Just to clarify, the certs are lost by DFP.. they still exist when running `docker secret ls`

**Comment by n1b0r** [comment]
could you provide the stack file ?

**Comment by n1b0r** [comment]
The secret feature is quite experimental, while its correctly working on my production server.

When DFPLE receive a /reconfigure request, it tries to generate or renew certs.
In secret mode, a new secret is created for new certs.
Then we check if DFP has these secrets loaded, if not we attach each secret to it.  If secrets have been updated, the DFP service will also restart and generate its new configuration based on secrets.

What did you try ? Once DFP service is created and has secrets attached, they should not be removed.

**Comment by patrickleet** [comment]
How is DFP is aware of the secrets? I thought you would need to configure that.

**Comment by n1b0r** [comment]
DFPLE updates DFP secrets usign **docker-py** with an [ugly POST request](https://github.com/n1b0r/docker-flow-proxy-letsencrypt/blob/master/app/dfple.py#L237) against docker socket. ([docker-py workaround](https://github.com/docker/docker-py/issues/1503) written at this time)

Once update is done, DFP is automatically restarted by docker engine (as a **docker service update --secret-add** would do)

**Comment by n1b0r** [comment]
did you get any chance to get it working ?

**Comment by hopkins-tk** [comment]
Not sure, if it is the case for you, but I was struggling with getting it work as well - in the end the root cause for me was using of an upper-case stack name _PROXY_ and not setting `DF_PROXY_SERVICE_NAME` correctly.

If you are using `stack deploy`, you need to use lowercase stack name and set `DF_PROXY_SERVICE_NAME` including the stack name and with matching case (there is exact match being performed).

**Comment by patrickleet** [comment]
I had it working, but when I added a new service with a different subdomain, the ssl certs were lost.

I then switched to using volumes instead because that worked for me.

**Comment by n1b0r** [comment]
Did you set the `le-certs:/etc/letsencrypt` volume on dfple service ? You have to set it in case you recreate dfple service.
