### ISSUE TITLE
Secrets are not being recreated when removed (Swarm cluster destroy)

### ISSUE THREAD

**Issue by hopkins-tk** [n1b0r/docker-flow-proxy-letsencrypt#9]
### Description:
We have a testing set-up where we are destroying & creating the Swarm cluster from scratch.

When there are certificates already generated and stored on `le-certs:/etc/letsencrypt` volume mount to `proxy-le`, they are not being regenerated (that is OK), but the secrets are not being recreated (not OK).

### How to reproduce:
1) Create cluster
2) Use secrets feature to propagate certificates to DFP
3) Destroy cluster
4) Create cluster
5) Redeploy your stack(s)
6) Certificates are not available to DFP

**Comment by n1b0r** [comment]
Hey tanks for tour report. I am in holidays this week but I Will have time To check your case next week.

**Comment by n1b0r** [comment]
This should be fixed in release 0.5, you should pull latest version. If not feel free to reopen.

**Comment by alexanderkjeldaas** [comment]
I'm seeing this behavior on latest.
